# Base configuration for DCCF robustness experiments
# This file contains the default parameters for all experiments

# Data parameters
data_path: "data/ratings.csv"
rating_threshold: 4.0
val_fraction: 0.1
test_fraction: 0.1

# Model parameters
embedding_dim: 64
learning_rate: 0.01
weight_decay: 0.000001

# Training parameters
epochs: 15
batch_size: 2048

# Evaluation parameters
k_eval: 20

# Noise parameters (will be overridden in specific experiments)
noise_level: 0.0
noise_schedule: "static"
noise_ramp_epochs: 10

# Reweighting parameters (will be overridden in specific experiments)
use_reweighting: false
reweight_alpha: 0.5
reweight_warmup_epochs: 10

# Output parameters
output_dir: "runs/base_experiment"
save_model: true

# System parameters
device: "auto"
random_seed: 42
